name: CI

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint and type-check the repo tooling
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm format-check

      - run: pnpm lint

      - run: pnpm type-check

  test:
    runs-on: ${{ matrix.os }}
    name: Test ${{ matrix.package }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        package:
          - expo-template-redux-typescript
          - rtk-app-structure-example
          - vite-template-redux

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: Set up environment variables
        if: ${{ matrix.os == 'windows-latest' }}
        run: echo "TEMP=$USERPROFILE\AppData\Local\Temp" >> $GITHUB_ENV

      - name: Scaffold, install, test, lint, and build ${{ matrix.package }}
        run: pnpm test:templates ${{ matrix.package }}

      - name: Did we fail?
        if: failure()
        working-directory: packages/${{ matrix.package }}
        run: ls -R
